version: "3"
services: 
  database:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
    volumes:
      - ./data/sqlserver:/var/opt/mssql/data
  server:
    build:
      context: ./
      dockerfile: server.Dockerfile
    ports: 
      - "5028:80"
      - "7028:443"
    depends_on: 
      - database
  web:
    build:
      context: ./
      dockerfile: web.Dockerfile
    ports: 
      - "5173:5173"
    depends_on: 
      - server
networks:
  server-net:
    driver: bridge